export default [
  {
    nome: "S. R. Feminino - Corte Longitudinal: Útero",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/cortelongitudinaldoutero",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Orgãos Genitais",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/orgaosgenitaisfemininos",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Ovário ",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/ovario",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Posição da Vagina na Pelve ",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/posicaodavaginanapelve",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Projeção dos Orgãos Genitais na Pelve ",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/projecaodosorgaosgenitaisfemininosnapelve",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Anexos e Topografia: Útero",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/uteroeanexostopografia",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Forma e Estrutura Anatômica: Útero e Tubas Uterinas",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/úteroetubasuterinasformaeestruturaanatômica",
    categoria:13 ,
  },
  {
    nome: "S. R. Feminino - Vagina",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"21/05/2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/vagina",
    categoria:13 ,
  },
  {
    nome: "Ceco e parte terminal do Íleo",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/cecoeparteterminaldoileo",
    categoria:13 ,
  },
  {
    nome: "Abdomen Superior: Cortes Horizontais",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Ricardo Alves Correa",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/corteshorizontaisdoabdomensuperior",
    categoria:13 ,
  },
  {
    nome: "Abdomen Superior 2: Cortes Horizontais",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/corteshorizontaisdoabdomensuperior2",
    categoria:13 ,
  },
  {
    nome: "Pâncreas e Duodeno: Drenagem Linfática",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/drenagemlinfaticadobacodopancreaseduodeno",
    categoria:13 ,
  },
  {
    nome: "Estômago: Drenagem Linfática",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/drenagemlinfaticadoestomago",
    categoria:13 ,
  },
  {
    nome: "Intestino Grosso: Drenagem Linfática",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/drenagemlinfaticadointestinogrosso",
    categoria:13 ,
  },
  {
    nome: "Estômago e Instestino Delgado: Drenagem Linfática e Invervação",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/drenagemlinfaticaeinervacaodoestomagoedointestinodelgado",
    categoria:13 ,
  },
  {
    nome: "Estômago e Instestino Delgado 2: Drenagem Linfática e Invervação",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/drenagemlinfaticaeinervacaodoestomagoedointestinodelgado2",
    categoria:13 ,
  },
  {
    nome: "Estômago e Duodeno: Drenagem Venosa",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/drenagemvenosadoestomagoedoduodeno",
    categoria:13 ,
  },
  {
    nome: "Estômago: Camadas Musculares",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/estomagocamadasmusculares",
    categoria:13 ,
  },
  {
    nome: "Fígado: Abertura Omento Menor",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/figadoaposaberturadoomentomenor",
    categoria:13 ,
  },
  {
    nome: "Inervação Autônoma do Intestino pelo Plexo Mesentérico-Superior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/inervacaoautonomadointestinopeloplexomesentericosuperior",
    categoria:13 ,
  },
  {
    nome: "Inervação do Fígado e da Vesícula Biliar: Estômago, Duodeno, Pâncres e Baço",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/inervacaodofigadodavesículabiliardoestomagododuodenodopancreasedobaco",
    categoria:13 ,
  },
  {
    nome: "Mesentérica Superior e Inferior: Irrigação do Intestino Grosso",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/irrigacaodointestinogrossopelasaamesentericassuperioreinferior",
    categoria:13 ,
  },
  {
    nome: "Linfono e Drenagem do Jejuno e Íleo",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/linfonodoseadrenagemdojejunoedoileo",
    categoria:13 ,
  },
  {
    nome: "Cavidade Abdominal: Posição do Fígado",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/posicaodofigadonacavidadeabdominal",
    categoria:13 ,
  },
  {
    nome: "Mesentérica Superior: Região e Ramos de Suprimento",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/regiaoeramosdesuprimentodaamesentericasuperior",
    categoria:13 ,
  },
  {
    nome: "Reto",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/reto",
    categoria:13 ,
  },
  {
    nome: "Reto e Canal Anal",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/retoecanalanal",
    categoria:13 ,
  },
  {
    nome: "Estômago: Superfície Interna ",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/superficieinternadoestomago",
    categoria:13 ,
  },
  {
    nome: "Tronco Celíaco e Artérias: Pâncreas, Duodeno e Baço",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/troncoceliacoearteriasparaopancreasduodenoebaco",
    categoria:13 ,
  },
  {
    nome: "Veias Estômago: Duodeno e Baço",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/veiasdoestomagoduodenoebaco",
    categoria:13 ,
  },
  {
    nome: "Vias Biliares e suas Relações",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/viasbiliaresesuasrelacoes",
    categoria:13 ,
  },
  {
    nome: "Visceras Abdominais: Vista-Posterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/viscerasabdominaisvistaposterior",
    categoria:13 ,
  },
  {
    nome: "Esôfago: Artéria e Veias",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo26-esôfagoartériaseveias",
    categoria:13 ,
  },
  {
    nome: "Esôfago: Corte Sagital Mediano",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo25-esôfagocortesagitalmediano",
    categoria:13 ,
  },
  {
    nome: "Defecação e Esvaziamento da Ampola do Reto",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo24-sequênciadeeventosdadefecaçãoesvaziamentodaampoladoreto",
    categoria:13 ,
  },
  {
    nome: "Defecação e Enchimento da Ampola do Reto",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo23-sequênciadeeventosdadefecaçãoenchimentodaampoladoreto",
    categoria:13 ,
  },
  {
    nome: "Fígado: Posição, Relações com Órgãos Adjacentes",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo22-fígadoposiçãoerelaçõescomórgãosadjacentes",
    categoria:13 ,
  },
  {
    nome: "Topografia do Reto",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo21-topografiadoreto",
    categoria:13 ,
  },
  {
    nome: "Fígado: Face Visceral",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo20-Fígado-face visceral",
    categoria:13 ,
  },
  {
    nome: "Fígado: Face Diafragmática",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo19-fígadofacediafragmática",
    categoria:13 ,
  },
  {
    nome: "Baço: Face Visceral",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo18-baçofacevisceral",
    categoria:13 ,
  },
  {
    nome: "Baço: Face Costal",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo17-baçofacecostal",
    categoria:13 ,
  },
  {
    nome: "Pâncreas: Posição e Trajeto do Ducto Pancreático",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Marcel Vitor Bravin Colnago",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo16-pâncreasposiçãoetrajetodoductopancreático",
    categoria:13 ,
  },
  {
    nome: "Intestino Delgado, Duodeno, Estruturas das Paredes e Sistemas de Ductos",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo15-intestinodelgadoduodenoestruturadaparedeesistemadeductos",
    categoria:13 ,
  },
  {
    nome: "Pâncreas: Vista-Anterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Marcel Vitor Bravin Colnago",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo14-pâncreasvistaanterior",
    categoria:13 ,
  },
  {
    nome: "Segmentos Anatômicos: Duodeno",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Douglas Rapcinski",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo13-segmentosanatômicosdoduodeno",
    categoria:13 ,
  },
  {
    nome: "Jejuno e Íleo",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo12-jejunoeÍleo",
    categoria:13 ,
  },
  {
    nome: "Intestino Grosso: Segmentos, Formas e Particularidades",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo11-intestinogrossosegmentosformaeparticularidades",
    categoria:13 ,
  },
  {
    nome: "Estômago",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo10-estomago",
    categoria:13 ,
  },
  {
    nome: "Sistema Digestório",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo9-sistemadigestório",
    categoria:13 ,
  },
  {
    nome: "Vísceras Abdominais: Vista-Anterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo7-víscerasabdominaisvistaanterior",
    categoria:13 ,
  },
  {
    nome: "Conteúdo Abdominal: Visão-Geral",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo8-conteúdoabdominalvisãogeral",
    categoria:13 ,
  },
  {
    nome: "Estômago: Morfologia Interna",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo6-estomagomorfologiainterna",
    categoria:13 ,
  },
  {
    nome: "Estômago: Forma e Estruturas Anatômicas",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo5-estomagoformaeestruturasanatomicas",
    categoria:13 ,
  },
  {
    nome: "Artérias de Estômago: Duodeno e Baço",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo4-artériasdeestômago,duodenoebaço",
    categoria:13 ,
  },
  {
    nome: "Leito do Estômago",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Chiara Kerolaine Beletato",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo3-leitodoestômago",
    categoria:13 ,
  },
  {
    nome: "Bolsa Omental: Vista-Anterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo2-bolsaomentalvistaanterior",
    categoria:13 ,
  },
  {
    nome: "Vista Anterior em de Cúbito Dorsal",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/capasistemadigestorio.png",
    url: "/jogar/jogo1-vistaanterioremdecúbitodorsal",
    categoria:13 ,
  },
  {
    nome: "Sistema Reprodutor Feminino",
    descricao: " Organize as Palavras em suas localidades corretas e verifique se acertou.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Carlos Augusto Cerillo Machado, Carolina Ferrari",
    data:"2024",
    imagem: "/img/imgsistemaRfeminino.png",
    url: "/jogar/sistemareprodutorfeminino",
    categoria:13 ,
  },
  {
    nome: "Laminário Artéria",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/laminarioarteria",
    categoria:16,
  },
  {
    nome: "Laminário Artéria - Parte 2",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/laminarioarteria2",
    categoria:16,
  },
  {
    nome: "Laminário Baço",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/LaminarioBaço",
    categoria:16,
  },
  {
    nome: "Laminário Baço - Poupas",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/LaminarioBaçoPoupas",
    categoria:16,
  },
  {
    nome: "Laminário Histologia - Vasos Sanguíneos",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/laminariohistologia-vasossanguineos",
    categoria:16,
  },
  {
    nome: "Laminário Linfonodo",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/LaminarioLinfonodo",
    categoria:16,
  },
  {
    nome: "Laminário Linfonodo - Parte 2",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/laminariolinfonodoparte2",
    categoria:16,
  },
  {
    nome: "Laminário Timo",
    descricao: "Arraste e solte de acordo com a cor da localidade.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Dayane Priscila dos Santos",
    data:"2024",
    imagem: "/img/laminariohistologia.png",
    url: "/jogar/Laminariotimo",
    categoria:16,

  },
  {
    nome: "Quiz Medicamentos - Parte 1",
    descricao: "Responda corretamente as questões.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga, Camila Perli Pinto ",
    data:"2024",
    imagem: "/img/quizmedicamentos1.png",
    url: "/jogar/quizmedicamentos1",
    categoria:8,
  },
  {
    nome: "Joelho: Parte 1",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Benito Marcelo Ferri",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/joelhoparte-1",
    categoria:17,
  },
  {
    nome: "Joelho Vista Anterior - Parte 1 ",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/joelhovistaanteriorparte-1",
    categoria:17,
  },
  {
    nome: "Membro Inferior - Vista Posterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/MembroInferior-VistaPosterior",
    categoria:17,
  },
  {
    nome: "Músculos e Nervação da Coxa - Vista Anterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/músculosenervaçãodecoxaVistaanterior",
    categoria:17,
  },
  {
    nome: "Pé: Parte 1",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/péparte-1",
    categoria:17,
  },
  {
    nome: "Perna Vista Posterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/perna-posterior",
    categoria:17,
  },
  {
    nome: "Perna Vista Anterior - Parte 1",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/perna-vista-anterior-parte-1",
    categoria:17,
  },
  {
    nome: "Perna Vista Anterior - Parte 2",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    data:"",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/perna-vista-anterior-parte-2",
    categoria:17,
  },
  {
    nome: "Perna - Vista Lateral",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/perna-vista-lateral",
    categoria:17,
  },
  {
    nome: "Perna - Vista Medial",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/perna-vista-medial",
    categoria:17,
  },
  {
    nome: "Pé - Vista Inferior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/pévistainferior",
    categoria:17,
  },
  {
    nome: "Plexo Lombar",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/plexo-lombar",
    categoria:17,
  },
  {
    nome: "Plexo Sacal",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/plexo-sacal",
    categoria:17,
  },
  {
    nome: "Quadril - Parte 1",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/quadril-parte-1",
    categoria:17,
  },
  {
    nome: "Quadril - Vista Posterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/quadril-vista-posterior",
    categoria:17,
  },
  {
    nome: "Radiologia Patológica - Encefalo 1",
    descricao: "Responda Corretamente as perguntas.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/encéfalo1.jpeg",
    url: "/jogar/RadiologiaPatologicaencefalo1",
    categoria:15,
  },
  {
    nome: "Radiologia Patológica - Encefalo 3",
    descricao: "Responda Corretamente as perguntas.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/encéfalo3.jpeg",
    url: "/jogar/RadiologiaPatologicaencefalo3",
    categoria:15,

  },
  {
    nome: "Região Poplítea - Vista Posterior",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/regiao-poplítea-visão-posterior",
    categoria:17,
  },
  {
    nome: "Coxa e Quadril - Região Posterior ",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/região-posterior-de-coxa-e-quadril",
    categoria:17,
  },
  {
    nome: "Coxa: Vista-Anterior.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/coxavistaanterior",
    categoria:17,
  },
  {
    nome: "Coxa: Vista-Posterior.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/coxavistaposterior",
    categoria:17,
  },
  {
    nome: "Face Anterior da Perna.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/faceanteriordaperna",
    categoria:17,
  },
  {
    nome: "Joelho: Parte 2 - Vista Lateral.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/joelhoparte2vistalateral",
    categoria:17,
  },
  {
    nome: "Ligamentos do Joelho.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/ligamentosjoelho",
    categoria:17,
  },
  {
    nome: "Pé: Parte 2.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/peparte2",
    categoria:17,
  },
  {
    nome: "Perna Anterior Parte 2: Articulação Aberta.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/pernaanterior2articulacaoaberta",
    categoria:17,
  },
  {
    nome: "Perna Anterior Parte 2: Vista Posterior.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/pernaanterior2vistaposterior",
    categoria:17,
  },
  {
    nome: "Perna Vista Posterior.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/pernavistaposterior",
    categoria:17,
  },
  {
    nome: "Quadril: Parte 2.",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/quadrilparte2",
    categoria:17,
  },
  {
    nome: "Região Dorsal do Pé",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/regiaodorsaldope",
    categoria:17,
  },
  {
    nome: "Coxa: Região Inguinal",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/regiaoinguinalcoxa",
    categoria:17,
  },
  {
    nome: "Região Posterior da Perna",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/regiaoposteriordaperna",
    categoria:17,
  },
  {
    nome: "Visão Lateral do Tornozelo",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/visaolateraltornozelo",
    categoria:17,
  },
  {
    nome: "Visão Medial do Tornozelo",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/visaomedialtornozelo",
    categoria:17,
  },
  {
    nome: "Coxa e Quadril: Vista Posterior Parte 1",
    descricao: "Toque na localidade correta correspondente à palavra exibida.",
    desenvolvedor:"Juan Manfrim Fernandes",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/vistaposteriorcoxaequadril1",
    categoria:17,
  },
  {
    nome: "Inserções do Quadril e Coxa - Parte 1",
    descricao: "Indique os nomes das partes do 'Inserções do Quadril e Coxa Parte 1' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/inserçõesmuscularesquadrilecoxap1_D2",
    categoria:17,
  },
  {
    nome: "Músculos da Coxa e Quadril",
    descricao: "Indique os nomes das partes do 'Músculos da Coxa e Quadril' corretamente.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/musculos-coxaequadril_D2",
    categoria:17,
  },
  {
    nome: "Músculos da Coxa",
    descricao: "Indique os nomes das partes do 'Músculos da Coxa' corretamente.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/musculo-da-coxa_D2",
    categoria:17,
  },
  {
    nome: "Músculos da Coxa - Dissecação Profunda",
    descricao: "Indique os nomes das partes do 'Músculos da Coxa - Dissecação Profunda' corretamente.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/musculosdacoxa-dissecacaoprofunda_D2",
    categoria:17,
  },
  {
    nome: "Inserções do Quadril e Coxa - Parte 2",
    descricao: "Indique os nomes das partes do 'Inserções do Quadril e Coxa Parte 2' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2024",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/inserçõesmuscularesquadrilecoxap2_D2",
    categoria:17,
  },
  {
    nome: "Sistema Respiratório Parte 1",
    descricao: "Indique os nomes das partes do 'Sistema Respiratório' corretamente.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistemarespiratoriop1.png",
    url: "/jogar/sistemarespiratoriop1_D2",
    categoria:13,
  },
  {
    nome: "Sistema Respiratório Parte 2",
    descricao: "Indique os nomes das partes do 'Sistema Respiratório Parte  2' corretamente.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistemarespiratoriop2.png",
    url: "/jogar/sistemarespiratoriop2_D2", 
    categoria:13 ,
  },
  {
    nome: "Parede Anterior do Tórax Vista Interna",
    descricao: "Indique os nomes das partes da 'Parede Anterior do Tórax Vista Interna' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Ricardo Alves Correa",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/paredeanteriordotoraxvistainterna_D2",
    categoria:5,
  },
  {
    nome: "Anatomia Tórax - Corte Transversal",
    descricao: "Indique os nomes das partes dos 'Anatomia Tórax - Corte Transversal' corretamente.",
    desenvolvedor:"Leandro Pinécio M.",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Ricardo Alves Correa, Luiz Fernando Machado",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/anatomiatorax-cortetransversal",
    categoria:17,
  },
  {
    nome: "Músculo - Visão Posterior Parte 2",
    descricao: "Indique os nomes das partes do 'Músculo - Visão Posterior Parte 2' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/músculos-visãoposteriorparte2",
    categoria:5,
  },
  {
    nome: "Músculo - Visão Posterior Parte 1",
    descricao: "Indique os nomes das partes do 'Músculo - Visão Posterior Parte 1' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/músculos-visãoposteriorparte1",
    categoria:5,
  },
  {
    nome: "Músculo - Visão Posterior Parte 3",
    descricao: "Indique os nomes das partes do 'Músculo - Visão Posterior Parte 3' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/músculos-visãoposteriorparte3",
    categoria:5,
  },
  {
    nome: "Anatomia Superficial - Membro Inferior",
    descricao: "Indique os nomes das partes da 'Anatomia Superficial - Membro Inferior' corretamente.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/anatomiasuperficialdomembroinferior",
    categoria:5,
  },
  {
    nome: "Anatomia Superficial - Membro Inferior Posterior",
    descricao: "Indique os nomes das partes da 'Anatomia Superficial - Membro Inferior Posterior' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/anatomia-superficial-membroinferiorposterior",
    categoria:5,
  },
  {
    nome: "Anatomia Superficial - Membro Inferior Frontal",
    descricao: "Indique os nomes das partes da 'Anatomia Superficial - Membro Inferior Frontal' corretamente.",
    desenvolvedor:"Leandro Pinecio Malizan",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/modeloanatomiamuscular.png",
    url: "/jogar/anatomia-superficial-membroinferiorfrontal",
    categoria:5,
  },
  {
    nome: "Preparo de medicamentos",
    descricao: "Passo a passo do Preparação á ministração de medicamentos",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/preparo-de-medicamentos.png",
    url: "/jogar/preparo-de-medicamentos", 
    categoria:6 ,
  },
  {
    nome: "Radiologia da Coluna Lombo-Sacra",
    descricao: "Arraste e solte corretamente as partes da 'Coluna Lombo-Sacra'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Douglas Rapcinski",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiacolunalombosacral",
    categoria:14,
  },
  {
    nome: "Identifique os Intrumentos Cirurgicos",
    descricao: "Acerte o nome e a mesa correta para cada instrumento cirúrgico.",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Marcel Vitor Bravin Colnago, Douglas Rapcinski ",
    data:"2022",
    imagem: "/img/instrumentacao-cirugica.png",
    url: "/jogar/instrumentacaocirurgica",
    categoria:9,
  },
  {
    nome: "Radiologia da Coxa",
    descricao: "Arraste e solte corretamente as partes da 'Coxa'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxcoxa",
    categoria:14,
  },
  {
    nome: "Radiologia da Patela",
    descricao: "Arraste e solte corretamente as partes da 'Patela'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxpatela",
    categoria:14,
  },
  {
    nome: "Radiologia do Torax 2",
    descricao: "Arraste e solte corretamente as partes da 'Torax'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxtorax2",
    categoria:14,
  },
  {
    nome: "Radiologia do Cotovelo",
    descricao: "Arraste e solte corretamente as partes do 'Cotovelo'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiacotovelo",
    categoria:14,
  },
  {
    nome: "Radiologia do Ombro",
    descricao: "Arraste e solte corretamente as partes do 'Ombro'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiadoombro",
    categoria:14,
  },
  {
    nome: "Radiologia do Pé Parte 1",
    descricao: "Arraste e solte corretamente as partes do 'Pé Parte 1'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiadopep1",
    categoria:14,
  },
  {
    nome: "Radiologia do Pé Parte 2",
    descricao: "Arraste e solte corretamente as partes do 'Pé Parte 2'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiadopep2",
    categoria:14,
  },
  {
    nome: "Radiologia do Pé Parte 3",
    descricao: "Arraste e solte corretamente as partes do 'Pé Parte 3'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiadopep3",
    categoria:14,
  },
  {
    nome: "Radiologia dos Membros Inferiores",
    descricao: "Arraste e solte corretamente as partes dos 'Membros Inferiores'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiamembrosinferiores",
    categoria:14,
  },
  {
    nome: "Radiologia do Joelho",
    descricao: "Arraste e solte corretamente as partes do 'Joelho'.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxjoelho",
    categoria:14,
  },
  {
    nome: "Radiologia da Coluna Lombar Parte 1 ",
    descricao: "Arraste e solte corretamente as partes da 'Coluna Lombar', vista Lateral.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxcolunalombar",
    categoria:14,
  },
  {
    nome: "Radiologia Tíbia e Fíbula",
    descricao: "Arraste e solte corretamente as partes da 'Tíbia e Fíbula.'",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxtibiaefibula",
    categoria:14,
  },
  {
    nome: "Radiologia Coluna Torácica",
    descricao: "Arraste e solte corretamente as partes da 'Coluna Torácica'",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/colunatoracicaraiox",
    categoria:14,
  },
  {
    nome: "Radiologia Da Mão",
    descricao: "Arraste e solte corretamente as partes da 'Mão', vista Frontal.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiadamao",
    categoria:14,
  },
  {
    nome: "Radiologia Coluna Cervical",
    descricao: "Arraste e solte corretamente as partes da 'Coluna Cervical', vista Frontal.",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiacolunacervical",
    categoria:14,
  },
  {
    nome: "Radiologia da Coluna Lombar Parte 2",
    descricao: "Arraste e solte corretamente as partes da 'Coluna Lombar', vista Posterior.",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/colunalombarparte2",
    categoria:14,
  },
  {
    nome: "Radiologia do Crânio Parte 1",
    descricao: "Arraste e solte corretamente as determinadas partes do 'Crânio'",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/cerebroraiox",
    categoria:14,
  },
  {
    nome: "Radiologia da Coluna Cervical Parte 2",
    descricao: "Arraste e solte corretamente as determinadas partes da 'Coluna Cervical Parte 2'",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiacolunacervicalp2",
    categoria:14,
  },
  {
    nome: "Radiologia do Crânio Parte 2",
    descricao: "Arraste e solte corretamente as determinadas partes do 'Crânio Parte 2'",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/raioxdocranioparte2",
    categoria:14,
  },
  {
    nome: "Radiologia do Tórax",
    descricao: "Arraste e solte corretamente as determinadas partes do 'Tórax'",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Matheus Guelssi dos Santos",
    data:"2023",
    imagem: "/img/anatomiaradiologica.png",
    url: "/jogar/radiologiadotorax", 
    categoria:14,
  },
  {
    nome: "Articulação temporomandibular",
    descricao: "Identificar a anatomia da articulação temporomandibular",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Luís Miguel Soares Vasconcelos Maia",
    data:"2023",
    imagem: "/img/atm.png",
    url: "/jogar/atm",
    categoria:4,
  },
  {
    nome: "Bases farmacológicas",
    descricao: "Saber identificar os tipos de medicamentos e seus usos",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/bases-farmocologicas.png",
    url: "/jogar/bases-farmacologicas",
    categoria:6,
  },
  {
    nome: "Ciclos de Krebs",
    descricao: "Identificar o ciclo",
    desenvolvedor:"Rafael Godoy, Leandro Pinécio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/ciclo-de-krebs.png",
    url: "/jogar/ciclo-de-krebs",
    categoria:10,
  },
  {
    nome: "Colesterol",
    descricao: "Identificar as funções da lipoproteina",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga",
    data:"2022",
    imagem: "/img/colesterol.png",
    url: "/jogar/colesterol",
    categoria:11,
  },
  {
    nome: "Coluna vertebral",
    descricao: "Identificação da coluna",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/coluna-vertebral.png  ",
    url: "/jogar/coluna-vertebral",
    categoria:14,
  },
  {
    nome: "Vascularização encefálica",
    descricao: "Identificar cada parte do cérebro",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/vascularizacao-encefalica.png",
    url: "/jogar/vascularizacao-encefalica",
    categoria:5,
  },
  {
    nome: "Cateterismo Vesical",
    descricao: "Identificar o canal vesical",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Marcel Vitor Bravin Colnago",
    data:"2022",
    imagem: "/img/cateterismo-vesical.png",
    url: "/jogar/cateterismo-vesical",
    categoria:7,
  },
  {
    nome: "Controle do Movimento Coporal",
    descricao: "Identificar os músculos responsáveis por cada movimento",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga",
    data:"2022",
    imagem: "/img/controle-movimento.png",
    url: "/jogar/controle-movimento",
    categoria:1 ,
  },
  {
    nome: "Características dos Componentes de uma Via Sensitiva",
    descricao: "Localizar os componentes das vias sensitivas",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2022",
    imagem: "/img/via-sensitiva.jpeg",
    url: "/jogar/via-sensitiva",
    categoria:5,
  },
  {
    nome: "Anatomia do Esterno",
    descricao: "Identificar as diferentes partes da parede torácica",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/torax.png",
    url: "/jogar/torax",
    categoria:4,
  },
  {
    nome: "Ausculta",
    descricao: "Fazer ausculta corretamente",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Ricardo Alves Correa",
    data:"2022",
    imagem: "/img/auscuta.png",
    url: "/jogar/ausculta",
    categoria:7,
  },
  {
    nome: "Pele",
    descricao: "Nomear corretamente cada ponto da anatomia da pele",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/pele.png",
    url: "/jogar/pele",
    categoria:13,
  },
  {
    nome: "Sangue",
    descricao: "Identificar cada elemento do sangue",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga",
    data:"2022",
    imagem: "/img/sangue.png",
    url: "/jogar/sangue",
    categoria:11,
  },
  {
    nome: "Topografia anatomica",
    descricao: "Nomear e identificar a topografia anatomica",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/topografia-anatomica.png",
    url: "/jogar/topografia-anatomica",
    categoria:1,
  },
  {
    nome: "Neuro anatomia da memória",
    descricao:"Identificar o nome de cada parte do cérebro responsavel por cada ciclo da memoria",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2022",
    imagem: "/img/neuroanatomia.png",
    url: "/jogar/neuro-anatomia-da-memoria",
    categoria:5,
  },
  {
    nome: "Instrumentação - montagem da mesa",
    descricao:
      "Monte a mesa com os intrumentos correros em seus respectivos setores",
      desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Marcel Vitor Bravin Colnago",
    data:"2023",
    imagem: "/img/instrumentacao.png",
    url: "/jogar/instrumentacao",
    categoria:9,
  },
  {
    nome: "Monitor cardíaco",
    descricao: "Leitura do monitor cardiaco de acordo com cada caso",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Ricardo Alves Correa",
    data:"2022",
    imagem: "/img/monitor-cardiaco.png",
    url: "/jogar/monitor-cardiaco",
    categoria:9,
  },
  {
    nome: "Show do milhão",
    descricao: "Responda corretamente as perguntas",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/show.png",
    url: "/jogar/show-do-milhao",
    categoria:8,
  },
  {
    nome: "Sistema auditivo",
    descricao: "Identificar e montar o sistema auditivo",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga, Luís Miguel Soares Vasconcelos Maia",
    data:"2023",
    imagem: "/img/sistema-auditivo.png",
    url: "/jogar/sistema-auditivo",
    categoria:13,
  },
  {
    nome: "Tireoide",
    descricao: "Responda corretamente as questões",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga",
    data:"2023",
    imagem: "/img/tireoide.png",
    url: "/jogar/tireoide", 
    categoria:13,
  },
  {
    nome: "Febre reumática",
    descricao: "Faça corretamente a auscuta e identificar o ciclo cardiaco",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2022",
    imagem: "/img/febre-reumatica.png",
    url: "/jogar/febre-reumatica",
    categoria:12,
  },
  {
    nome: "Medula e plexo",
    descricao: "Identificar cada parte que se pede",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga",
    data:"2022",
    imagem: "/img/modula-pleixo.png",
    url: "/jogar/medula-e-plexo",
    categoria:5,
  },
  {
    nome: "Anatomia do olho",
    descricao: "Identificar a anatomia do olho",
    desenvolvedor:"Rafael Godoy, Leandro Pinécio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2023",
    imagem: "/img/olho.png",
    url: "/jogar/anatomia-do-olho",
    categoria:3,

  },
  {
    nome: "Ventilador",
    descricao:
      "Prepar o ventilador de forma que atenda a prescrição do paciente",
      desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Ricardo Alves Correa",
    data:"2022",
    imagem: "/img/respirador.png",
    url: "/jogar/ventilador",
    categoria:9, 
  },
  {
    nome: "Sistema renal",
    descricao: "Identificar o sistema renal",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Marcel Vitor Bravin Colnago",
    data:"2023",
    imagem: "/img/sistema-renal.png",
    url: "/jogar/sistema-renal",
    categoria:13,
  },
  {
    nome: "Sistema respiratório",
    descricao: "Identificar o sistema respiratorio",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistema-respiratorio.png",
    url: "/jogar/sistema-respiratorio",
    categoria:13,
  },
  {
    nome: "Sistema reprodutor masculino",
    descricao: "Identificar cada parte do sistema reprodutor masculino",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Marcel Vitor Bravin Colnago",
    data:"2023",
    imagem: "/img/sistema-reprodutor-masculino.png",
    url: "/jogar/sistema-reprodutor-masculino",
    categoria:13,
  },
  {
    nome: "Sistema digestório",
    descricao: "Identificar o que faz cada ciclo da digestão",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Douglas Rapcinski",
    data:"2023",
    imagem: "/img/digestorio.png",
    url: "/jogar/sistema-digestorio",
    categoria:13,
  },
  {
    nome: "Sifilis",
    descricao: "Se informar sobre a doença",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga, Flavia Afonso Pinto Fuzii",
    data:"2023",
    imagem: "/img/sifilis.png",
    url: "/jogar/sifilis",
    categoria:12,
  },
  {
    nome: "Cérebro Quiz 1",
    descricao: "Responda as perguntas sobre os Lobos Cerebrais",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/cerebro-quiz.png",
    url: "/jogar/cerebro-quiz",
    categoria:8,
  },
  {
    nome: "Leishmaniose",
    descricao: "Nomear cada parte do ciclo",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga, Flavia Afonso Pinto Fuzii",
    data:"2022",
    imagem: "/img/leishmaniose.png",
    url: "/jogar/leishmaniose",
    categoria:12,
  },
  {
    nome: "Sensação somatica pt1",
    descricao: "Identificar cada parte e suas relações",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2022",
    imagem: "/img/sensacao-somatica-1.png",
    url: "/jogar/sensacao-somatica-pt1",
    categoria:5,
  },
  {
    nome: "Sensação somatica pt2",
    descricao: "Identificar cada parte e suas relações",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sensacao-somatica-2.png",
    url: "/jogar/sensacao-somatica-pt2", 
    categoria:5,
  },
  {
    nome: "Sensação somatica pt3",
    descricao: "Identificar cada parte e suas relações",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2022",
    imagem: "/img/sensacao-somatica-3.png",
    url: "/jogar/sensacao-somatica-pt3",
    categoria:5,
  },
  {
    nome: "Sensação somatica pt4",
    descricao: "Identificar cada parte e suas relações",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2022",
    imagem: "/img/sensacao-somatica-4.png",
    url: "/jogar/sensacao-somatica-pt4",
    categoria:5,
  },
  {
    nome: "Vias ópticas",
    descricao: "Identificar cada parte das vias opticas",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Barbara Evelin Gonçalves Barboza",
    data:"2022",
    imagem: "/img/vias-opticas.png",
    url: "/jogar/via-optica",
    categoria:3 ,

  },
  {
    nome: "Cascata de defesa celular",
    descricao: "Complete o fluxo de defesa celular",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/cascata-defesa-celular.png",
    url: "/jogar/cascata-de-defesa-celular", 
    categoria:11,
  },
  {
    nome: "Estrutura Celular",
    descricao: "Complete a estrutura celular",
    desenvolvedor:"Rafael Godoy, Leandro Pinecio, Juan Manfrim",
    suporte:"Alan Henrique De Lazari",
    revisor:"Camila Gomes Braga",
    data:"2022",
    imagem: "/img/celula.png",
    url: "/jogar/celula",
    categoria:10, 
  },
  {
    nome: "Fisiologia do sangue",
    descricao: "Complete fluxograma",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Camila Gomes Braga",
    data:"2022",
    imagem: "/img/fisiologia-do-sangue.png",
    url: "/jogar/fisiologia-do-sangue",
    categoria:11,
  },
  {
    nome: "Instrumentos medicos",
    descricao: "Passe pelos desafios e identifique os instrumentos",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Ricardo Alves Correa, Marcel Vitor Bravin Colnago ",
    data:"2022",
    imagem: "/img/identifique-os-instrumentos.png",
    url: "/jogar/instrumentos-medicos",
    categoria:9, 
  },
  {
    nome: "SE Vértebra Cervical Parte 1",
    descricao: "Arraste e solte, identificando cada parte do osso 'Vértebra Cervical' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/vertebrascervicalp1", 
    categoria:4,
  },
  {
    nome: "SE Vértebra Cervical Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Vértebra Cervical' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/vertebracervicalp2",
    categoria:4,
  },
  {
    nome: "SE Úmero ",
    descricao: "Arraste e solte, identificando cada parte do osso 'Úmero' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/umero",
    categoria:4,
  },
  {
    nome: "SE Tíbia e Fíbula Parte 1 ",
    descricao: "Arraste e solte, identificando cada parte do osso 'Tíbia e Fíbula' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/tibiaefibulap1",
    categoria:4,
  },
  {
    nome: "SE Tíbia e Fíbula Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Tíbia e Fíbula' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/tibiaefibulap2",
    categoria:4,
  },
  {
    nome: "SE Sacro",
    descricao: "Arraste e solte, identificando cada parte do osso 'Sacro' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/sacro",
    categoria:4,
  },
  {
    nome: "SE Rádio e Ulna Parte 1",
    descricao: "Arraste e solte, identificando cada parte do osso 'Rádio e Ulna' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/radioulnap1",
    categoria:4,
  },
  {
    nome: "SE Rádio e Ulna Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Rádio e Ulna' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/radioulnap2",
    categoria:4,
  },
  {
    nome: "SE Pé Parte 1",
    descricao: "Arraste e solte, identificando cada parte do osso 'Pé' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/pép1",
    categoria:4,
  },
  {
    nome: "SE Pé Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Pé' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/pép2",
    categoria:4,
  },
  {
    nome: "SE Pé Parte 3",
    descricao: "Arraste e solte, identificando cada parte do osso 'Pé' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Eloy Okabayashi Fuzzi",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/pép3",
    categoria:4,
  },
  {
    nome: "SE Quadril Parte 1",
    descricao: "Arraste e solte, identificando cada parte do osso 'Quadril' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/ossosdoquadrilp1",
    categoria:4,
  },
  {
    nome: "SE Quadril Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Quadril' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Cynthia Priscilla do Nascimento Bonato Panizzon",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/ossodoquadrilp2",
    categoria:4,
  },
  {
    nome: "SE Nervos da Escápula",
    descricao: "Arraste e solte, identificando cada parte dos Nervos da Escápula ",
    desenvolvedor:"Matheus Mariot",
    suporte:"Alan Henrique De Lazari, Rafael Godoy",
    revisor:"Alan Henrique De Lazari",
    data:"2022",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/nervosdaescapula",
    categoria:4,
  },
  {
    nome: "SE Membro Superior",
    descricao: "Arraste e solte, identificando cada parte do osso 'Membro Superior' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/membrosuperior",
    categoria:4,
  },
  {
    nome: "SE Membro Inferior",
    descricao: "Arraste e solte, identificando cada parte do osso 'Membro Inferior' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/membroinferior",
    categoria:4,
  },
  {
    nome: "SE Mãos",
    descricao: "Arraste e solte, identificando cada parte do osso 'Mãos' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/maos",
    categoria:4,
  },
  {
    nome: "SE Fêmur Parte 1",
    descricao: "Arraste e solte, identificando cada parte do osso 'Fêmur' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/femur",
    categoria:4,
  },
  {
    nome: "SE Fêmur Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Fêmur' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/femurp2",
    categoria:4,
  },
  {
    nome: "SE Fêmur Parte 3",
    descricao: "Arraste e solte, identificando cada parte do osso 'Fêmur' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/femurp3",
    categoria:4,
  },
  {
    nome: "SE Esterno",
    descricao: "Arraste e solte, identificando cada parte do osso 'Esterno' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/esterno",
    categoria:4,
  },
  {
    nome: "SE Escápula",
    descricao: "Arraste e solte, identificando cada parte do osso 'Escápula' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/escapula",
    categoria:4,
  },
  {
    nome: "SE Costela",
    descricao: "Arraste e solte, identificando cada parte do osso 'Costela' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Alan Henrique De Lazari",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/costela",
    categoria:4,
  },
  {
    nome: "SE Coluna Vertebral Parte 1",
    descricao: "Arraste e solte, identificando cada parte do osso 'Coluna Vertebral' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/colunavertebralp1",
    categoria:4,
  },
  {
    nome: "SE Coluna Vertebral Parte 2",
    descricao: "Arraste e solte, identificando cada parte do osso 'Coluna Vertebral' ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Benito Marcelo Ferri",
    data:"2023",
    imagem: "/img/sistema-esqueletico.png",
    url: "/jogar/colunavertebralp2",
    categoria:4,
  },
  {
    nome: "Anatomia do Coração 2",
    descricao: "Arraste e solte, identificando cada parte do coração ",
    desenvolvedor:"Rafael Godoy Pinguelo",
    suporte:"Alan Henrique De Lazari",
    revisor:"Ricardo Alves Correa, Luiz Fernando Machado ",
    data:"2023",
    imagem: "/img/anatomiacoracao.png",
    url: "/jogar/anatomiadocoracao2",
    categoria:2,

  },
];
